# Generated by Django 2.0.13 on 2019-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('job', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=300)),
                ('moving_date', models.DateTimeField(blank=True, null=True)),
                ('deal_type', models.CharField(max_length=100)),
                ('residence_type', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('roomfloor', models.CharField(max_length=100)),
                ('deposit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manage_price', models.IntegerField()),
                ('room_size', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=300)),
                ('detail', models.TextField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
