# Generated by Django 2.0.13 on 2019-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='deposit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='manage_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='moving_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
