# Generated by Django 2.0.13 on 2019-06-02 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190602_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
