# Generated by Django 2.0.13 on 2019-06-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190602_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='auto_increment_id',
            new_name='data_id',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='published_date',
            new_name='enroll_date',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='price',
            new_name='monthly_price',
        ),
    ]
